#ifndef D12_DRAW_VERTEX_H
#define D12_DRAW_VERTEX_H
#include <DirectXMath.h>
#include <d3d12.h>

struct Vertex1 {
  DirectX::XMFLOAT3 pos;
  DirectX::XMFLOAT4 col;
};

inline const D3D12_INPUT_ELEMENT_DESC InputLayout1[] =
{
  { "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0,
    D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
  { "COLOR", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT,
    D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
};

#endif // D12_DRAW_VERTEX_H
